### ISSUE TITLE
undefined symbol during tests with tf 1.13.0.dev20190226

### ISSUE THREAD

**Issue by Daiver** [pmh47/dirt#10]
Hi! Thank you for your project!
I tried to run tests (`python tests/square_test.py`) with tf-nightly and obtained following error

```
Traceback (most recent call last):
  File "tests/square_test.py", line 4, in <module>
    import dirt
  File "/home/daiver/coding/dirt/.venv/lib/python2.7/site-packages/dirt/__init__.py", line 2, in <module>
    from rasterise_ops import rasterise, rasterise_batch
  File "/home/daiver/coding/dirt/.venv/lib/python2.7/site-packages/dirt/rasterise_ops.py", line 7, in <module>
    _rasterise_module = tf.load_op_library(_lib_path + '/librasterise.so')
  File "/home/daiver/coding/dirt/.venv/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/daiver/coding/dirt/.venv/lib/python2.7/site-packages/dirt/librasterise.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesB5cxx11ESt16initializer_listIN4absl11string_viewEE

```

My system info:
```
cat /etc/issue
Ubuntu 18.04.2 LTS \n \l

python --version
Python 2.7.15rc1

pip show tf-nightly-gpu
Name: tf-nightly-gpu
Version: 1.13.0.dev20190226
```

**Comment by pmh47** [comment]
Unfortunately I can't replicate this. Does it work with stable tensorflow (1.12)? Was DIRT definitely built against the same tensorflow version (specifically, the same libtensorflow_framework.so) as it's running with? Also try running `ldd dirt/librasterise.so` and check it points to the same tensorflow library as your venv is using.

**Comment by Daiver** [comment]
@pmh47 thank you for answer!
Currently i have cuda 10 on my system. As far as i know stable tensorflow uses cuda 9. Unfortunately currently i'm not skilled enough to manage how to use tensorflow with local versions of cuda. Anyway I'll try to change my systems cuda in a few days.

```
ldd .venv/lib/python2.7/site-packages/dirt/librasterise.so 
	linux-vdso.so.1 (0x00007ffc43d1e000)
	libEGL.so.1 => /usr/lib/x86_64-linux-gnu/libEGL.so.1 (0x00007fd9119cb000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fd91173f000)
	libtensorflow_framework.so => /home/daiver/coding/dirt/.venv/lib/python2.7/site-packages/tensorflow/libtensorflow_framework.so (0x00007fd9104e6000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd9102de000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd9100bf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd90febb000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd90fb32000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd90f794000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd90f57c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd90f18b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd911ed5000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fd90eed5000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fd90eca4000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fd90e96c000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fd90e744000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fd90e540000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fd90e33a000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fd90e125000)
```
As far as i can see `librasterise` uses `virtualenv` version of tf
```
libtensorflow_framework.so => /home/daiver/coding/dirt/.venv/lib/python2.7/site-packages/tensorflow/libtensorflow_framework.so (0x00007fd9104e6000)
```

```
>>> import tensorflow as tf
>>> tf
<module 'tensorflow' from '/home/daiver/coding/dirt/.venv/lib/python2.7/site-packages/tensorflow/__init__.pyc'>
>>> 
```
So probably dirt linked against right version of tf

**Comment by pmh47** [comment]
Yes, the output from `ldd` looks fine -- I'm not sure what is causing the problem. Let me know once you've had time to try with tensorflow 1.12.

**Comment by Daiver** [comment]
Just created fresh virtual env and installed tf via `pip2 install tensorflow-gpu==1.12`
`pip2 install .` was ok, but `python2 tests/square_test.py` gives me
```
(.venv) ➜  dirt git:(master) ✗ python2 tests/square_test.py 
Traceback (most recent call last):
  File "tests/square_test.py", line 4, in <module>
    import dirt
  File "/home/daiver/coding/dirt/.venv/lib/python2.7/site-packages/dirt/__init__.py", line 2, in <module>
    from rasterise_ops import rasterise, rasterise_batch
  File "/home/daiver/coding/dirt/.venv/lib/python2.7/site-packages/dirt/rasterise_ops.py", line 7, in <module>
    _rasterise_module = tf.load_op_library(_lib_path + '/librasterise.so')
  File "/home/daiver/coding/dirt/.venv/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/daiver/coding/dirt/.venv/lib/python2.7/site-packages/dirt/librasterise.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesB5cxx11ESt16initializer_listIN4absl11string_viewEE
```

**Comment by pmh47** [comment]
So far, I can't reproduce this. Could you try a development build (i.e. run cmake explicitly from dirt/build folder), and verify that the tensorflow library path listed in the cmake cache corresponds to the one being used at runtime? Also, it is possible there's a big enough mismatch in g++ versions between what was used to build libtensorflow_framework and the version you used to build DIRT (meaning that the ABI is different) -- what version are you using (again, the cmake cache should specify this)?

**Comment by ronixy** [comment]
@pmh47  I also got this undefined symbol error, using tensorflow 1.4.0 and cuda 8.0

**Comment by pmh47** [comment]
Yes; apparently Tensorflow's official (pip) builds are done with gcc 4.x; see [here](https://www.tensorflow.org/install/source#bazel_build_options). So users with gcc 5.1 or newer who are using the official Tensorflow package (and not building from source) need to set `_GLIBCXX_USE_CXX11_ABI=0` when building DIRT to ensure binary compatibility, as @ronixy noted. I'll update the build script accordingly, and add a note to the README.

**Comment by fasogbon** [comment]
Thanks! Your suggestions for release build worked perfectly fine

set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -ffast-math  **-D_GLIBCXX_USE_CXX11_ABI=0**")
