### ISSUE TITLE
How to install GLVND OpenGL libaries?

### ISSUE THREAD

**Issue by mehameha998** [pmh47/dirt#15]
Soorry to ask this simply question. I'm really new in  OpenGL and others. I was pulzeed by segementation error several days. I guess the lack of GLVND OpenGL is the key point. 
SO anyone can teach me how to install GLVND OpenGL libaries?? And what the difference between LEGACY and GLVND? And the link of mesa3D and those two?

**Comment by pmh47** [comment]
Hi @mehameha998 
You do not need to install GLVND (in fact you can only do so by building it from source). GLVND is used to support both mesa's and nvidia's GL drivers side-by-side. However, Mesa is not required for DIRT, and can conflict with the nvidia libraries (safer not to have it installed). The version of libOpenGL / libGL / libEGL from the nvidia driver always uses GLVND internally; Ubuntu 18.04 and newer use GLVND for mesa too.
