### ISSUE TITLE
gl_common.h:42:42: error: ‘PFNEGLQUERYDEVICESEXTPROC’ was not declared in this scope

### ISSUE THREAD

**Issue by MISSXUAN0** [pmh47/dirt#26]
(octopus) test@True3d-pc2:~/octopus/dirt-master/build$ cmake ../csrc
-- The CXX compiler identification is GNU 4.8.4
-- The CUDA compiler identification is NVIDIA 9.0.176
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda-9.0/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-9.0/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/test/octopus/dirt-master/build
(octopus) test@True3d-pc2:~/octopus/dirt-master/build$ make
Scanning dependencies of target rasterise
[ 14%] Building CXX object CMakeFiles/rasterise.dir/rasterise_egl.cpp.o
In file included from /home/test/octopus/dirt-master/csrc/rasterise_egl.cpp:28:0:
/home/test/octopus/dirt-master/csrc/gl_common.h: In function ‘void gl_common::initialise_context(int)’:
/home/test/octopus/dirt-master/csrc/gl_common.h:42:42: error: ‘PFNEGLQUERYDEVICESEXTPROC’ was not declared in this scope
         auto const eglQueryDevicesEXT = (PFNEGLQUERYDEVICESEXTPROC) eglGetProcAddress("eglQueryDevicesEXT");
                                          ^
/home/test/octopus/dirt-master/csrc/gl_common.h:43:47: error: ‘PFNEGLQUERYDEVICEATTRIBEXTPROC’ was not declared in this scope
         auto const eglQueryDeviceAttribEXT = (PFNEGLQUERYDEVICEATTRIBEXTPROC) eglGetProcAddress("eglQueryDeviceAttribEXT");
                                               ^
/home/test/octopus/dirt-master/csrc/gl_common.h:44:48: error: ‘PFNEGLGETPLATFORMDISPLAYEXTPROC’ was not declared in this scope
         auto const eglGetPlatformDisplayEXT = (PFNEGLGETPLATFORMDISPLAYEXTPROC) eglGetProcAddress("eglGetPlatformDisplayEXT");
                                                ^
/home/test/octopus/dirt-master/csrc/gl_common.h:50:9: error: ‘EGLDeviceEXT’ was not declared in this scope
         EGLDeviceEXT eglDevs[MAX_DEVICES];
         ^
/home/test/octopus/dirt-master/csrc/gl_common.h:50:22: error: expected ‘;’ before ‘eglDevs’
         EGLDeviceEXT eglDevs[MAX_DEVICES];
                      ^
/home/test/octopus/dirt-master/csrc/gl_common.h:52:46: error: ‘eglDevs’ was not declared in this scope
         if (!eglQueryDevicesEXT(MAX_DEVICES, eglDevs, &numDevices) || numDevices == 0)
                                              ^
/home/test/octopus/dirt-master/csrc/gl_common.h:59:17: error: ‘EGLAttrib’ was not declared in this scope
                 EGLAttrib cudaDeviceId = -1;
                 ^
/home/test/octopus/dirt-master/csrc/gl_common.h:59:27: error: expected ‘;’ before ‘cudaDeviceId’
                 EGLAttrib cudaDeviceId = -1;
                           ^
/home/test/octopus/dirt-master/csrc/gl_common.h:60:41: error: ‘eglDevs’ was not declared in this scope
                 eglQueryDeviceAttribEXT(eglDevs[eglDeviceIndex], EGL_CUDA_DEVICE_NV, &cudaDeviceId);
                                         ^
/home/test/octopus/dirt-master/csrc/gl_common.h:60:66: error: ‘EGL_CUDA_DEVICE_NV’ was not declared in this scope
                 eglQueryDeviceAttribEXT(eglDevs[eglDeviceIndex], EGL_CUDA_DEVICE_NV, &cudaDeviceId);
                                                                  ^
/home/test/octopus/dirt-master/csrc/gl_common.h:60:87: error: ‘cudaDeviceId’ was not declared in this scope
                 eglQueryDeviceAttribEXT(eglDevs[eglDeviceIndex], EGL_CUDA_DEVICE_NV, &cudaDeviceId);
                                                                                       ^
In file included from /home/test/octopus/dirt-master/csrc/rasterise_egl.cpp:28:0:
/home/test/octopus/dirt-master/csrc/gl_common.h:70:54: error: ‘EGL_PLATFORM_DEVICE_EXT’ was not declared in this scope
         auto const eglDpy = eglGetPlatformDisplayEXT(EGL_PLATFORM_DEVICE_EXT, eglDevs[eglDeviceIndex], 0);
                                                      ^
/home/test/octopus/dirt-master/csrc/gl_common.h:70:79: error: ‘eglDevs’ was not declared in this scope
         auto const eglDpy = eglGetPlatformDisplayEXT(EGL_PLATFORM_DEVICE_EXT, eglDevs[eglDeviceIndex], 0);
                                                                               ^
/home/test/octopus/dirt-master/csrc/rasterise_egl.cpp: In member function ‘void RegisteredBuffer::ensure_size(const size_t&)’:
/home/test/wangxuan/octopus/dirt-master/csrc/rasterise_egl.cpp:81:76: error: ‘glNamedBufferData’ was not declared in this scope
         glNamedBufferData(gl_index, required_size, nullptr, GL_DYNAMIC_COPY);
                                                                            ^
make[2]: *** [CMakeFiles/rasterise.dir/rasterise_egl.cpp.o] Error 1
make[1]: *** [CMakeFiles/rasterise.dir/all] Error 2
make: *** [all] Error 2

**Comment by pmh47** [comment]
The symbols that are missing are in `dirt/external/EGL/eglext.h`, which should be included in the build include path automatically. Did you change any include paths in CMakeLists or the cmake cache? Alternatively, if you have another, older copy of EGL headers somewhere on the system include path (e.g. from Mesa), that could cause this. Check what `EGL_INCLUDE_DIR` is set to in the cmake cache, and change it to point to `/home/test/octopus/dirt-master/external/EGL`.
For the later error about glNamedBufferData, follow the instructions in the [README](https://github.com/pmh47/dirt#troubleshooting) for using Khronos's GL headers (again, I think your system is using an older version).

**Comment by MISSXUAN0** [comment]
@pmh47 
Thank you! I finally succeed.
 Your statement is very correct. Indeed, this is mesa caused the first problem.The later error about glNamedBufferData be solved by follow the instructions in the README. 
Moreover,my systerm is Ubuntu14,it's too older and always have many problems.
I have encountered another problem.
[ 71%] Building CXX object CMakeFiles/rasterise.dir/shaders.cpp.o
make[2]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libGL.so', needed by `CMakeFiles/rasterise.dir/cmake_device_link.o'.  Stop.
[https://github.com/RobotLocomotion/drake/issues/2087](url) follow this question can be solved.
