### ISSUE TITLE
Segmentation fault using GL functions

### ISSUE THREAD

**Issue by radmahdi** [pmh47/dirt#33]
Dirt is successfully installed, but the process finishes with exit code #139, when it wants to use a gl function (e.g. `glGetString(GL_RENDERER)` ) in gl_common.h.

I set OpenGL preference to GLVND  in cmake as suggested, but it did not help:
`set(OpenGL_GL_PREFERENCE "GLVND")`

Any idea would be appreciated. Thanks!

**Comment by pmh47** [comment]
Please give the output of
```
import dirt.rasterise_ops
import subprocess
subprocess.call(['ldd', dirt.rasterise_ops._lib_path + '/librasterise.so'])
```
and
```
ls -l /usr/lib/*/*GL*
```
and also try making the changes to CMakeLists described at the bottom of https://github.com/pmh47/dirt/issues/2#issuecomment-427884756

**Comment by radmahdi** [comment]
Thanks for the prompt response. 

The output of `subprocess.call(['ldd', dirt.rasterise_ops._lib_path + '/librasterise.so'])` is:

`linux-vdso.so.1 =>  (0x00007ffef98c1000)
	libEGL.so.1 => /usr/lib/nvidia-384/libEGL.so.1 (0x00007f32b5f05000)
	libGL.so.1 => /usr/lib/nvidia-384/libGL.so.1 (0x00007f32b5bc3000)
	libtensorflow_framework.so => /home/mahdi/anaconda3/envs/GenHOPE/lib/python3.5/site-packages/tensorflow/libtensorflow_framework.so (0x00007f32b4c56000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f32b4a4e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f32b4831000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f32b462d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f32b424a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f32b3f41000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f32b3d29000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f32b395f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f32b6406000)
	libGLdispatch.so.0 => /usr/lib/nvidia-384/libGLdispatch.so.0 (0x00007f32b3691000)
	libnvidia-tls.so.384.130 => /usr/lib/nvidia-384/tls/libnvidia-tls.so.384.130 (0x00007f32b348d000)
	libnvidia-glcore.so.384.130 => /usr/lib/nvidia-384/libnvidia-glcore.so.384.130 (0x00007f32b15d1000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f32b1297000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f32b1085000)
	libcublas.so.9.0 => /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcublas.so.9.0 (0x00007f32adc4f000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f32acdd1000)
	libcudnn.so.7 => /usr/lib/x86_64-linux-gnu/libcudnn.so.7 (0x00007f329a6bf000)
	libcufft.so.9.0 => /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcufft.so.9.0 (0x00007f329261e000)
	libcurand.so.9.0 => /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcurand.so.9.0 (0x00007f328e6ba000)
	libcudart.so.9.0 => /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0 (0x00007f328e44d000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f328e22b000)
	libnvidia-fatbinaryloader.so.384.130 => /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.130 (0x00007f328dfd9000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f328ddd5000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f328dbcf000)`

And `ls -l /usr/lib/*/*GL*` returns:

`lrwxrwxrwx 1 root root      24 Mär  7 16:46 /usr/lib/nvidia-384/libEGL_nvidia.so.0 -> libEGL_nvidia.so.384.130
-rw-r--r-- 1 root root 1313208 Mär 21  2018 /usr/lib/nvidia-384/libEGL_nvidia.so.384.130
lrwxrwxrwx 1 root root      17 Mär  7 16:46 /usr/lib/nvidia-384/libEGL.so -> libEGL.so.384.130
lrwxrwxrwx 1 root root      17 Mär  7 16:46 /usr/lib/nvidia-384/libEGL.so.1 -> libEGL.so.384.130
-rw-r--r-- 1 root root   73328 Mär 21  2018 /usr/lib/nvidia-384/libEGL.so.1.1.0
-rw-r--r-- 1 root root   20192 Mär 21  2018 /usr/lib/nvidia-384/libEGL.so.384.130
-rw-r--r-- 1 root root  711864 Mär 21  2018 /usr/lib/nvidia-384/libGLdispatch.so.0
lrwxrwxrwx 1 root root      30 Mär  7 16:46 /usr/lib/nvidia-384/libGLESv1_CM_nvidia.so.1 -> libGLESv1_CM_nvidia.so.384.130
-rw-r--r-- 1 root root   54392 Mär 21  2018 /usr/lib/nvidia-384/libGLESv1_CM_nvidia.so.384.130
lrwxrwxrwx 1 root root      17 Mär  7 16:46 /usr/lib/nvidia-384/libGLESv1_CM.so -> libGLESv1_CM.so.1
lrwxrwxrwx 1 root root      21 Feb 13 13:32 /usr/lib/nvidia-384/libGLESv1_CM.so.1 -> libGLESv1_CM.so.1.2.0
-rw-r--r-- 1 root root   43696 Mär 21  2018 /usr/lib/nvidia-384/libGLESv1_CM.so.1.2.0
lrwxrwxrwx 1 root root      27 Mär  7 16:46 /usr/lib/nvidia-384/libGLESv2_nvidia.so.2 -> libGLESv2_nvidia.so.384.130
-rw-r--r-- 1 root root   86232 Mär 21  2018 /usr/lib/nvidia-384/libGLESv2_nvidia.so.384.130
lrwxrwxrwx 1 root root      14 Mär  7 16:46 /usr/lib/nvidia-384/libGLESv2.so -> libGLESv2.so.2
lrwxrwxrwx 1 root root      18 Feb 13 13:32 /usr/lib/nvidia-384/libGLESv2.so.2 -> libGLESv2.so.2.1.0
-rw-r--r-- 1 root root   83280 Mär 21  2018 /usr/lib/nvidia-384/libGLESv2.so.2.1.0
lrwxrwxrwx 1 root root      10 Mär  7 16:46 /usr/lib/nvidia-384/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      16 Mär  7 16:46 /usr/lib/nvidia-384/libGL.so.1 -> libGL.so.384.130
-rw-r--r-- 1 root root  665720 Mär 21  2018 /usr/lib/nvidia-384/libGL.so.1.7.0
-rw-r--r-- 1 root root 1291320 Mär 21  2018 /usr/lib/nvidia-384/libGL.so.384.130
lrwxrwxrwx 1 root root      24 Mär  7 16:46 /usr/lib/nvidia-384/libGLX_indirect.so.0 -> libGLX_nvidia.so.384.130
lrwxrwxrwx 1 root root      24 Mär  7 16:46 /usr/lib/nvidia-384/libGLX_nvidia.so.0 -> libGLX_nvidia.so.384.130
-rw-r--r-- 1 root root 1291320 Mär 21  2018 /usr/lib/nvidia-384/libGLX_nvidia.so.384.130
lrwxrwxrwx 1 root root      11 Mär  7 16:46 /usr/lib/nvidia-384/libGLX.so -> libGLX.so.0
-rw-r--r-- 1 root root   65840 Mär 21  2018 /usr/lib/nvidia-384/libGLX.so.0
lrwxrwxrwx 1 root root      14 Mär  7 16:46 /usr/lib/nvidia-384/libOpenGL.so -> libOpenGL.so.0
-rw-r--r-- 1 root root  211728 Mär 21  2018 /usr/lib/nvidia-384/libOpenGL.so.0
lrwxrwxrwx 1 root root      18 Jun 14  2018 /usr/lib/x86_64-linux-gnu/libEGL.so -> mesa-egl/libEGL.so
lrwxrwxrwx 1 root root      19 Feb 13 13:25 /usr/lib/x86_64-linux-gnu/libGLEWmx.so.1.13 -> libGLEWmx.so.1.13.0
-rw-r--r-- 1 root root  448632 Nov 10  2015 /usr/lib/x86_64-linux-gnu/libGLEWmx.so.1.13.0
lrwxrwxrwx 1 root root      17 Feb 13 13:25 /usr/lib/x86_64-linux-gnu/libGLEW.so.1.13 -> libGLEW.so.1.13.0
-rw-r--r-- 1 root root  514176 Nov 10  2015 /usr/lib/x86_64-linux-gnu/libGLEW.so.1.13.0
lrwxrwxrwx 1 root root      13 Jun 14  2018 /usr/lib/x86_64-linux-gnu/libGL.so -> mesa/libGL.so
-rw-r--r-- 1 root root  911218 Okt 23  2015 /usr/lib/x86_64-linux-gnu/libGLU.a
lrwxrwxrwx 1 root root      15 Okt 23  2015 /usr/lib/x86_64-linux-gnu/libGLU.so -> libGLU.so.1.3.1
lrwxrwxrwx 1 root root      15 Feb 13 13:25 /usr/lib/x86_64-linux-gnu/libGLU.so.1 -> libGLU.so.1.3.1
-rw-r--r-- 1 root root  453352 Okt 23  2015 /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
lrwxrwxrwx 1 root root      21 Feb 11 19:12 /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5 -> libQt5OpenGL.so.5.5.1
lrwxrwxrwx 1 root root      21 Feb 11 19:12 /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.5 -> libQt5OpenGL.so.5.5.1
-rw-r--r-- 1 root root  362752 Feb 11 19:13 /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.5.1
`

Changing line 5 of Cmake to ` Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY)` gives the following error:
`Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY)`

**Comment by pmh47** [comment]
Your libraries look ok, but cmake is failing to find them.
With CMakeLists line 5 changed to `find_package(OpenGL REQUIRED COMPONENTS OpenGL EGL)`
add `-D_OPENGL_LIB_PATH=/usr/lib/nvidia-384` to the cmake invocation (see https://github.com/pmh47/dirt/issues/2#issuecomment-483189003).

**Comment by radmahdi** [comment]
Cool!

Applying the followings:
`change line 5 to find_package(OpenGL REQUIRED COMPONENTS OpenGL EGL)
comment line 9
change line 42 to target_link_libraries(rasterise PRIVATE OpenGL::OpenGL OpenGL::EGL ${Tensorflow_LIBRARY})`

and running cmake using `cmake ../csrc/ -D_OPENGL_LIB_PATH=/usr/lib/nvidia-384` seems to solved the issue. 
Thanks for you the help!
