### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by wolf943134497** [pmh47/dirt#42]
Building wheels for collected packages: dirt
  Building wheel for dirt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dl/anaconda2/envs/tf-g/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-jXBqjA/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-jXBqjA/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-nMxDpP --python-tag cp27
       cwd: /tmp/pip-req-build-jXBqjA/
  Complete output (69 lines):
  running bdist_wheel
  running build
  -- The CXX compiler identification is GNU 5.4.0
  -- The CUDA compiler identification is unknown
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Check for working CUDA compiler: /usr/bin/nvcc
  -- Check for working CUDA compiler: /usr/bin/nvcc -- broken
  CMake Error at /opt/cmake-3.10.3/share/cmake-3.10/Modules/CMakeTestCUDACompiler.cmake:46 (message):
    The CUDA compiler

      "/usr/bin/nvcc"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: /tmp/pip-req-build-jXBqjA/build/CMakeFiles/CMakeTmp

**Comment by pmh47** [comment]
Apparently your cuda compiler `nvcc` is broken. What does running `/usr/bin/nvcc --version` give? What version of cuda do you have?

**Comment by wolf943134497** [comment]
hi @pmh47, Thank you for your reply !  
Cuda compilation tools, release 9.0, V9.0.176, /usr/bin/nvcc is a soft link (/usr/local/cuda/bin/nvcc) .

**Comment by pmh47** [comment]
That's strange; your configuration of nvcc 9 + gcc 5.4 + cmake 3.10 should work correctly. I think there would have been more lines of output after `Change Dir: /tmp/...` in your original post, which should say what the actual error from nvcc was -- could you paste all of that output here?

**Comment by wolf943134497** [comment]
CMake Error at /opt/cmake-3.12.4/share/cmake-3.12/Modules/CMakeTestCUDACompiler.cmake:46 (message):
      The CUDA compiler
        "/usr/bin/nvcc"
      is not able to compile a simple test program.
      It fails with the following output:
        Change Dir: /tmp/pip-req-build-l1ejzutl/build/CMakeFiles/CMakeTmp
        Run Build Command:"/usr/bin/make" "cmTC_0cce6/fast"
        /usr/bin/make -f CMakeFiles/cmTC_0cce6.dir/build.make CMakeFiles/cmTC_0cce6.dir/build
        make[1]: Entering directory '/tmp/pip-req-build-l1ejzutl/build/CMakeFiles/CMakeTmp'
        Building CUDA object CMakeFiles/cmTC_0cce6.dir/main.cu.o
        /usr/bin/nvcc     -x cu -c /tmp/pip-req-build-l1ejzutl/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_0cce6.dir/main.cu.o
        nvcc fatal   : Path to libdevice library not specified
        CMakeFiles/cmTC_0cce6.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_0cce6.dir/main.cu.o' failed
        make[1]: *** [CMakeFiles/cmTC_0cce6.dir/main.cu.o] Error 1
        make[1]: Leaving directory '/tmp/pip-req-build-l1ejzutl/build/CMakeFiles/CMakeTmp'
        Makefile:121: recipe for target 'cmTC_0cce6/fast' failed
        make: *** [cmTC_0cce6/fast] Error 2
      CMake will not be able to correctly generate this project.
    Call Stack (most recent call first):
      CMakeLists.txt:3 (project)
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-l1ejzutl/build/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-req-build-l1ejzutl/build/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-l1ejzutl/setup.py", line 50, in <module>
        'Programming Language :: Python :: 3.7',
      File "/home/dl/anaconda3/envs/gwm/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/dl/anaconda3/envs/gwm/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)

maybe python 3.7 works?  Can you tell me which version of python/anaconda/GL/ works ?
dependencies may conflict !  Thanks!

**Comment by pmh47** [comment]
This is not a problem with dependencies (nor with DIRT itself); rather, your cuda toolkit installation is broken somehow. Googling the actual error `nvcc fatal : Path to libdevice library not specified` will give you some possible solutions.

Python 3.6 and 3.7 work fine, any conda that gives you tensorflow-gpu 1.6 or newer, and OpenGL from any nvidia driver newer than v367.

I'll close this issue as it's not a problem with DIRT.
