### ISSUE TITLE
texture rendering artifact

### ISSUE THREAD

**Issue by shinxg** [pmh47/dirt#44]
Thanks @pmh47  for releasing the code. I have tried some demos using my own data. Some artifact appeared when I tested``samples/textured.py``.  
![image](https://user-images.githubusercontent.com/20951414/65426253-6aa64480-de42-11e9-934e-e5800ed71d5c.png)
I have modified the code slightly(just the input part). Here are the [code and data](https://drive.google.com/file/d/1_EiLY1POiBhQYQUPiiK-BzLEXN8EEu01/view?usp=sharing).
Could you please explain what causes such blemish? Really appreciate your help!

**Comment by pmh47** [comment]
OBJ files have vertex indices starting at one, but DIRT assumes they start at zero. Change line 70 of your code to `cube_faces = F.astype(np.int64) - 1` and it works fine.

**Comment by shinxg** [comment]
> OBJ files have vertex indices starting at one, but DIRT assumes they start at zero. Change line 70 of your code to `cube_faces = F.astype(np.int64) - 1` and it works fine.

Fool me. Thanks for the quick and accurate reply!
