### ISSUE TITLE
Can dirt support a laptop without GPU?

### ISSUE THREAD

**Issue by Silverster98** [pmh47/dirt#58]
I want to install dirt and use it, but my laptop doesn't have GPU. I just want to use cpu to run. Can I install and use it successfully?

**Comment by pmh47** [comment]
Unfortunately not -- it requires an nvidia gpu. There is no cpu implementation of the ops.

**Comment by MaxMayya** [comment]
So only Nvidia GPUs? I want to install DIRT on a mac, is that impossible?

**Comment by pmh47** [comment]
@MaxMayya Yes, only Nvidia GPUs are supported, therefore difficult to get it working on a mac.
