### ISSUE TITLE
Error:tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by EnochChan97** [pmh47/dirt#62]
Hi author!I'sorry to bother you but i encountered a problem when import dirt.my environment is as follow: ubuntu18.04 tensorflow-gpu=2.1 python=2.7

`Traceback (most recent call last):
File "infer_single.py", line 9, in
from model.octopus import Octopus
File "/home/chensien/octopus/model/octopus.py", line 16, in
from render.render_layer import RenderLayer
File "/home/chensien/octopus/render/render_layer.py", line 1, in
from render import render_colored_batch
File "/home/chensien/octopus/render/render.py", line 1, in
import dirt
File "/home/chensien/anaconda3/envs/octopus/lib/python2.7/site-packages/dirt/init.py", line 2, in
from .rasterise_ops import rasterise, rasterise_batch, rasterise_deferred, rasterise_batch_deferred
File "/home/chensien/anaconda3/envs/octopus/lib/python2.7/site-packages/dirt/rasterise_ops.py", line 6, in
_rasterise_module = tf.load_op_library(_lib_path + '/librasterise.so')
File "/home/chensien/anaconda3/envs/octopus/lib/python2.7/site-packages/tensorflow_core/python/framework/load_library.py", line 58, in load_op_library
lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so.1: cannot open shared object file: No such file or directory`

i check the the path "/home/chensien/anaconda3/envs/octopus/lib/python2.7/site-packages/dirt" and libtensorflow_framework.so.1 is exists.I'd be pretty appreciate if u offer some advice!thx!

**Comment by pmh47** [comment]
It looks like you somehow built DIRT using a different version of tensorflow (1.x), and then installed it in a conda env with tensorflow 2.1. Did you do a development-mode install (i.e. `cmake` followed by `pip install -e .`)? If so, delete the cmake build folder and rebuild, making sure your octopus conda env is activated beforehand.

**Comment by EnochChan97** [comment]
thanks for replying.Actually i didn't do a development-mode.I create a new conda env, install in development mode and then i get another problem:

`Traceback (most recent call last):  File "square_test.py", line 4, in <module>    import dirt  File "/home/chensien/octopus/dirt/dirt/__init__.py", line 2, in <module>    from .rasterise_ops import rasterise, rasterise_batch, rasterise_deferred, rasterise_batch_deferred  File "/home/chensien/octopus/dirt/dirt/rasterise_ops.py", line 6, in <module>    _rasterise_module = tf.load_op_library(_lib_path + '/librasterise.so')  File "/home/chensien/anaconda3/envs/octopus/lib/python2.7/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library    lib_handle = py_tf.TF_LoadLibrary(library_filename)tensorflow.python.framework.errors_impl.NotFoundError: /home/chensien/octopus/dirt/dirt/librasterise.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesB5cxx11ESt16initializer_listIN4absl11string_viewEE`

**Comment by pmh47** [comment]
gcc 5.4 on Ubuntu 18.04 is an unusual combination that I cannot test easily. The default system gcc version for Ubuntu 18.04 (i.e. gcc 7.4) seems to work correctly, combined with the python & tf versions you said (py27 / tf210, both from conda/main).

In your original install, without development mode, if you still have the conda env, could you do `conda list` and paste the results? It looks like some tensorflow 1 & 2 got mixed up somehow.

**Comment by EnochChan97** [comment]
I already removed the previous conda env.As you said,there are different version of tensorflow in the conda env.After checking my cuda version,i think problem is the mismatch of cuda version and tensorflow instead of gcc.So i reinstalled DIRT with tf1.12,and it works^ ^  Much thx for your  help !
