### ISSUE TITLE
Question about texture.

### ISSUE THREAD

**Issue by Frank-Dz** [pmh47/dirt#63]
Hi~ Thanks for your great work! It is fantastic!

Here I have several questions:
According to the readme:
> see samples for source code. The first uses simple monochromatic diffuse lighting calculated per-vertex and interpolated with Gouraud shading; the others use per-pixel (deferred) lighting and texture calculations.

Seems like if the one wants to get texture calculations involved, he/she must use the deferred mode (```pixels = dirt.rasterise_deferred```)?

And I tried to switch the ```dirt.rasterise```, it told me that some keyword arguments do not exist.
So, I am a little confused.

I want to ask is there an online reference manual for these details? Because I think there is not much description of these technical details in the paper, and the content provided by readme in this repo is a little rough.

Sorry for my first attempt, the problem may be a bit stupid! Anyone can help.

Thanks in advance.

**Comment by pmh47** [comment]
Sadly there is no documentation aside from what is at the top of each function, and the samples. I might write a proper guide, sometime.

Yes, you need `rasterise_deferred` for anything with texture.

**Comment by Frank-Dz** [comment]
> Sadly there is no documentation aside from what is at the top of each function, and the samples. I might write a proper guide, sometime.
> 
> Yes, you need `rasterise_deferred` for anything with texture.

If this is the case, I will keep looking forward to it! thank you very much! Your patient response is very encouraging. Hope this project keeps getting better! Thanks again!

Best,
Frank
