### ISSUE TITLE
How to change camera model to weak perspective projection

### ISSUE THREAD

**Issue by ffiioonnaa** [pmh47/dirt#66]
Hi,
It seems that dirt can only support perspective projection, for me the effect of perspective is too obvious. Is there anyway to change the camera model to support weak perspective projection or orthographic projection?

**Comment by ffiioonnaa** [comment]
Sorry, I just found out someone already mentioned this,I'll close this issue

**Comment by Frank-Dz** [comment]
> Sorry, I just found out someone already mentioned this,I'll close this issue

Hi~ I also want to use a weak-perspective camera. Yet currently I am struggling with other problems in DIRT. So maybe I will do that several day later and then share it. It depends.

To define your personal camera, please have a look at ```dirt\matrics.py line 110```
![image](https://user-images.githubusercontent.com/55009565/80448174-073b4280-894e-11ea-903b-f1cc1dd2502d.png)
