### ISSUE TITLE
none of 2 egl devices matches the active cuda device

### ISSUE THREAD

**Issue by Xinxiang7** [pmh47/dirt#68]
I complete installation with pip install -e . But when testing dirt with python test/square_test.py, I get the error as follows:
`2020-04-30 14:42:44.755471: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-30 14:42:44.776764: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2592000000 Hz
2020-04-30 14:42:44.777851: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x559774aa3e50 executing computations on platform Host. Devices:
2020-04-30 14:42:44.777887: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-04-30 14:42:44.866383: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-30 14:42:44.866620: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.2
pciBusID: 0000:01:00.0
totalMemory: 5.79GiB freeMemory: 5.32GiB
2020-04-30 14:42:44.866634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-04-30 14:42:44.866967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-30 14:42:44.866976: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-04-30 14:42:44.866980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-04-30 14:42:44.867032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5149 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-04-30 14:42:44.868070: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x559775355a80 executing computations on platform CUDA. Devices:
2020-04-30 14:42:44.868082: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2060, Compute Capability 7.5
565656565656565656565656565656565656565656565656565656565656
2020-04-30 14:42:44.951381: I /home/jiangcm/PycharmProjects/mgn/test/dirt/csrc/gl_common.h:61] eglQueryDeviceAttribEXT returns 0
2020-04-30 14:42:44.951398: I /home/jiangcm/PycharmProjects/mgn/test/dirt/csrc/gl_common.h:62] eglGetError returns 12292
2020-04-30 14:42:44.951403: I /home/jiangcm/PycharmProjects/mgn/test/dirt/csrc/gl_common.h:61] eglQueryDeviceAttribEXT returns 0
2020-04-30 14:42:44.951406: I /home/jiangcm/PycharmProjects/mgn/test/dirt/csrc/gl_common.h:62] eglGetError returns 12292
2020-04-30 14:42:44.951410: F /home/jiangcm/PycharmProjects/mgn/test/dirt/csrc/gl_common.h:67] none of 2 egl devices matches the active cuda device
nizaidadfaAborted (core dumped)`

what did I seach: 
- I add `LOG(INFO) << "eglQueryDeviceAttribEXT returns " <<` at the start of line 60, and `LOG(INFO) << "eglGetError returns " << eglGetError();` at line61.
The rusult is :
`eglQueryDeviceAttribEXT returns 0`
'eglGetError returns 12292'
- my Ubuntu version is 16.04, nvidia-440, cuda-10, cudnn-7.4
- the result of `ls -l /usr/lib*/*/*GL*`:
`lrwxrwxrwx 1 root root      23 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.0 -> libEGL_nvidia.so.440.64
-rwxr-xr-x 1 root root 1285296 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.440.64
lrwxrwxrwx 1 root root      11 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libEGL.so -> libEGL.so.1
lrwxrwxrwx 1 root root      15 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libEGL.so.1 -> libEGL.so.1.1.0
-rwxr-xr-x 1 root root   73312 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libEGL.so.1.1.0
-rwxr-xr-x 1 root root  732400 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0
lrwxrwxrwx 1 root root      29 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.1 -> libGLESv1_CM_nvidia.so.440.64
-rwxr-xr-x 1 root root   63696 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.440.64
lrwxrwxrwx 1 root root      17 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLESv1_CM.so -> libGLESv1_CM.so.1
lrwxrwxrwx 1 root root      21 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLESv1_CM.so.1 -> libGLESv1_CM.so.1.2.0
-rwxr-xr-x 1 root root   43696 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLESv1_CM.so.1.2.0
lrwxrwxrwx 1 root root      26 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.2 -> libGLESv2_nvidia.so.440.64
-rwxr-xr-x 1 root root  111416 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.440.64
lrwxrwxrwx 1 root root      14 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLESv2.so -> libGLESv2.so.2
lrwxrwxrwx 1 root root      18 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLESv2.so.2 -> libGLESv2.so.2.1.0
-rwxr-xr-x 1 root root   83280 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLESv2.so.2.1.0
lrwxrwxrwx 1 root root      19 Apr  3 11:29 /usr/lib/x86_64-linux-gnu/libGLEWmx.so.1.13 -> libGLEWmx.so.1.13.0
-rw-r--r-- 1 root root  448632 Nov 10  2015 /usr/lib/x86_64-linux-gnu/libGLEWmx.so.1.13.0
lrwxrwxrwx 1 root root      17 Nov 10  2015 /usr/lib/x86_64-linux-gnu/libGLEW.so -> libGLEW.so.1.13.0
lrwxrwxrwx 1 root root      17 Apr  3 11:29 /usr/lib/x86_64-linux-gnu/libGLEW.so.1.13 -> libGLEW.so.1.13.0
-rw-r--r-- 1 root root  514176 Nov 10  2015 /usr/lib/x86_64-linux-gnu/libGLEW.so.1.13.0
-rw-r--r-- 1 root root     671 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGL.la
lrwxrwxrwx 1 root root      10 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      14 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGL.so.1 -> libGL.so.1.7.0
-rwxr-xr-x 1 root root  685848 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGL.so.1.7.0
-rw-r--r-- 1 root root  911218 Oct 24  2015 /usr/lib/x86_64-linux-gnu/libGLU.a
lrwxrwxrwx 1 root root      15 Oct 24  2015 /usr/lib/x86_64-linux-gnu/libGLU.so -> libGLU.so.1.3.1
lrwxrwxrwx 1 root root      15 Apr  3 11:29 /usr/lib/x86_64-linux-gnu/libGLU.so.1 -> libGLU.so.1.3.1
-rw-r--r-- 1 root root  453352 Oct 24  2015 /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
lrwxrwxrwx 1 root root      23 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLX_indirect.so.0 -> libGLX_nvidia.so.440.64
lrwxrwxrwx 1 root root      23 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0 -> libGLX_nvidia.so.440.64
-rwxr-xr-x 1 root root 1114816 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.440.64
lrwxrwxrwx 1 root root      11 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLX.so -> libGLX.so.0
-rwxr-xr-x 1 root root   65096 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libGLX.so.0
lrwxrwxrwx 1 root root      14 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libOpenGL.so -> libOpenGL.so.0
-rwxr-xr-x 1 root root  215824 Apr 30 14:18 /usr/lib/x86_64-linux-gnu/libOpenGL.so.0
lrwxrwxrwx 1 root root      21 Feb 10 03:42 /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5 -> libQt5OpenGL.so.5.5.1
lrwxrwxrwx 1 root root      21 Feb 10 03:42 /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.5 -> libQt5OpenGL.so.5.5.1
-rw-r--r-- 1 root root  362752 Feb 10 03:43 /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.5.1
lrwxrwxrwx 1 root root      20 Apr  5  2016 /usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4 -> libQtOpenGL.so.4.8.7
lrwxrwxrwx 1 root root      20 Apr  5  2016 /usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4.8 -> libQtOpenGL.so.4.8.7
-rw-r--r-- 1 root root 1052024 Apr  5  2016 /usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4.8.7`

what I did there after:
1. uninstalled Nvidia driver and dirt
2. reinstalled Nvidia driver and dirt

After all these, I still doesn't solve the problem. Please do me a favor.

**Comment by Xinxiang7** [comment]
@pmh47 Thanks for your reply.
The output of `ldd dirt/librasterise.so`:
`	linux-vdso.so.1 =>  (0x00007ffd9f3e7000)
	libEGL.so.1 => /usr/local/lib/x86_64-linux-gnu/libEGL.so.1 (0x00007f40f271f000)
	libOpenGL.so.0 => /usr/lib/x86_64-linux-gnu/libOpenGL.so.0 (0x00007f40f24ea000)
	libtensorflow_framework.so => not found
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f40f22e2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f40f20c5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f40f1ec1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f40f1b3f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f40f1836000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f40f1620000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f40f1256000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f40f2c74000)
	libgbm.so.1 => /usr/local/lib/x86_64-linux-gnu/libgbm.so.1 (0x00007f40f1047000)
	libglapi.so.0 => /usr/local/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f40f0e15000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f40f0c13000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f40f09f1000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f40f07ec000)
	libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007f40f05e4000)
	libdrm.so.2 => /usr/local/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f40f03d2000)
	libwayland-client.so.0 => /usr/local/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f40f01c3000)
	libwayland-server.so.0 => /usr/local/lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007f40effaf000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f40efd86000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f40efb83000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f40ef980000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f40ef779000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f40ef576000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f40ef2a3000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f40ef09f000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f40eee99000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f40eec91000)`

When I search `LD_LIBRARY_PATH` in ~/.bashrc, I found this:
`# cuda path
export PATH=/usr/local/cuda-10.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH`
And I didn't find any set with `LD_PRELOAD` environment variables.

**Comment by Xinxiang7** [comment]
@pmh47 It's easier to read: 
	linux-vdso.so.1 =>  (0x00007ffd9f3e7000)
	libEGL.so.1 => /usr/local/lib/x86_64-linux-gnu/libEGL.so.1 (0x00007f40f271f000)
	libOpenGL.so.0 => /usr/lib/x86_64-linux-gnu/libOpenGL.so.0 (0x00007f40f24ea000)
	libtensorflow_framework.so => not found
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f40f22e2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f40f20c5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f40f1ec1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f40f1b3f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f40f1836000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f40f1620000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f40f1256000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f40f2c74000)
	libgbm.so.1 => /usr/local/lib/x86_64-linux-gnu/libgbm.so.1 (0x00007f40f1047000)
	libglapi.so.0 => /usr/local/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f40f0e15000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f40f0c13000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f40f09f1000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f40f07ec000)
	libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007f40f05e4000)
	libdrm.so.2 => /usr/local/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f40f03d2000)
	libwayland-client.so.0 => /usr/local/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f40f01c3000)
	libwayland-server.so.0 => /usr/local/lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007f40effaf000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f40efd86000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f40efb83000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f40ef980000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f40ef779000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f40ef576000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f40ef2a3000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f40ef09f000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f40eee99000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f40eec91000)

**Comment by pmh47** [comment]
`ldd` shows libEGL to be taken from `/usr/local/lib/...`, whereas I think the version in `/usr/lib/...` is correct. Try building with `CMAKE_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu` and/or running square_test with `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libEGL.so` set.

**Comment by Xinxiang7** [comment]
@pmh47 It works! Thanks for your detail replay.
I add  `CMAKE_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu` in ~/.bashrc file and then reinstall the dirt.
Thanks again.
