### ISSUE TITLE
Is ‘split_vertices_by_face’ an essential step?

### ISSUE THREAD

**Issue by ffiioonnaa** [pmh47/dirt#73]
Hi, I find the operation to split vertices by face made the number of vertices too much,Can I skip this step? Does this have an effect on gradient back propagation?

**Comment by pmh47** [comment]
It is not required for correct gradients. It is useful if you want flat shading rather than Gouraud shading, and because `dirt.matrices.vertex_normals` is/was slower than `dirt.matrices.vertex_normals_pre_split`.

**Comment by ffiioonnaa** [comment]
Get it, thanks~
