### ISSUE TITLE
librasterise.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PrimeDLY** [pmh47/dirt#75]
I have a different problem from Enoch Chan 97（Users of another Issues）, I check the path:`/home/dengly/anaconda3/envs/mgn/lib/python3.7/site-packages/dirt-0.3.0-py3.7.egg/dirt/librasterise.so` and this file does not exist. 

Here is my envs:
vmware15(I'm using virtual machines)
ubuntu18.04  
tensorflow-gpu=2.2.0  
python=3.7  

First of all, how can I get this file:"librasterise.so"? In addition, should I downgrade the version to use at present?I'd be very grateful if u could give me some advice!

**Comment by pmh47** [comment]
`librasterise.so` should be built automatically when DIRT is installed. Was any other error reported during the installation? Did you do a development-mode install (i.e. run cmake manually, then `pip install -e .`) or just a regular install with pip?

I've not tested DIRT with tf 2.2 yet -- so you could try downgrading to 2.1, which works.

**Comment by PrimeDLY** [comment]
Thank you very much. I'm sorry it took so long to reply.I can install dirt successfully after downgrading the tf version.The official document has the best matching version, I should have seen it earlier.
