### ISSUE TITLE
Render depth and silhouette

### ISSUE THREAD

**Issue by dihuangdh** [pmh47/dirt#76]
Hi @pmh47 

Can dirt render depth and silhouette? How ? 

Thanks.

**Comment by pmh47** [comment]
Yes, this can be done using the usual `rasterise` or  `rasterise_batch` -- pass the depths (i.e. negative view-space z-coordinates) as one vertex color channel (e.g. red channel), and all ones as another (e.g. green), then split the final image channels, i.e. red will be a depth-map and green the silhouette. For background, use a large value for red (so points where there is no object are given large depth), and zero for green.
