### ISSUE TITLE
The paper in IJCV shows the rendering detials, but I also have some question about it's process

### ISSUE THREAD

**Issue by ljx970128** [pmh47/dirt#77]
When use the subdivision method, the decoder net will output the mesh parameters include vertex offsets. I want to know the specific format of these vertex offsets, whether to include only the coordinates of surface points(98 vertices, 294 parameters). 
The faces in "sample" are pre-defined, so in your paper's experiment these faces how to get?
The decoder net would output rotation parameter, what's different between it and the encoder's output theta, the pose parameter.
@pmh47  hope to receive your reply.

**Comment by pmh47** [comment]
Closing as this is not related to DIRT itself (I replied to you by email re the IJCV paper).
