### ISSUE TITLE
how to directly bind RGB to the vertices of each 3D model when rendering?

### ISSUE THREAD

**Issue by Frank-Dz** [pmh47/dirt#79]
In the dirt, how to directly bind RGB to the vertices of each 3D model when rendering, instead of using UVmap-based textures. Best show some demo codes~

Thanks in advance!
Best,

**Comment by pmh47** [comment]
`samples/simple.py` shows how to do this. If instead you want per-pixel not per-vertex lighting, see `samples/deferred.py`.
