### ISSUE TITLE
error when installing on windows

### ISSUE THREAD

**Issue by jiangolder** [pmh47/dirt#88]
Hi I am installing with windows using pip install. I will appreciate it if you can help me to solve the errors.

The errors are:
Requirement already satisfied: tensorflow-gpu>=1.6 in c:\users\think\anaconda3\lib\site-packages (from dirt==0.3.0) (1.15.0)
Requirement already satisfied: numpy in c:\users\think\anaconda3\lib\site-packages (from dirt==0.3.0) (1.18.1)
Requirement already satisfied: wheel>=0.26 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (0.35.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (3.3.0)
Requirement already satisfied: protobuf>=3.6.1 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (3.11.3)
Requirement already satisfied: wrapt>=1.11.1 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (1.12.1)
Requirement already satisfied: google-pasta>=0.1.6 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (0.2.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (1.1.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (1.1.2)
Requirement already satisfied: gast==0.2.2 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (0.2.2)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (1.10.0)
Requirement already satisfied: six>=1.10.0 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (1.15.0)
Requirement already satisfied: astor>=0.6.0 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (0.6.2)
Requirement already satisfied: keras-applications>=1.0.8 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (1.0.8)
Requirement already satisfied: absl-py>=0.7.0 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (0.11.0)
Requirement already satisfied: tensorboard<1.16.0,>=1.15.0 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (1.15.0)
Requirement already satisfied: tensorflow-estimator==1.15.1 in c:\users\think\anaconda3\lib\site-packages (from tensorflow-gpu>=1.6->dirt==0.3.0) (1.15.1)
Requirement already satisfied: setuptools in c:\users\think\anaconda3\lib\site-packages (from protobuf>=3.6.1->tensorflow-gpu>=1.6->dirt==0.3.0) (50.3.0)
Requirement already satisfied: h5py in c:\users\think\anaconda3\lib\site-packages (from keras-applications>=1.0.8->tensorflow-gpu>=1.6->dirt==0.3.0) (3.1.0)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\think\anaconda3\lib\site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow-gpu>=1.6->dirt==0.3.0) (0.14.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\think\anaconda3\lib\site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow-gpu>=1.6->dirt==0.3.0) (2.6.11)
Requirement already satisfied: cached-property; python_version < "3.8" in c:\users\think\anaconda3\lib\site-packages (from h5py->keras-applications>=1.0.8->tensorflow-gpu>=1.6->dirt==0.3.0) (1.5.2)
Building wheels for collected packages: dirt
  Building wheel for dirt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\think\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-build-nxljb91b\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-build-nxljb91b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-wheel-dywbg2lm'
       cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-nxljb91b\
  Complete output (29 lines):
  running bdist_wheel
  running build
  CMake Error: The current CMakeCache.txt directory C:/Users/Public/Documents/Wondershare/CreatorTemp/pip-req-build-nxljb91b/build/CMakeCache.txt is different than the directory g:/Hand-imitation-learning/dirt/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  CMake Error: The source "C:/Users/Public/Documents/Wondershare/CreatorTemp/pip-req-build-nxljb91b/csrc/CMakeLists.txt" does not match the source "G:/Hand-imitation-learning/dirt/csrc/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-nxljb91b\setup.py", line 50, in <module>
      'Programming Language :: Python :: 3.7',
    File "C:\Users\think\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\think\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\think\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\think\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\think\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\Users\think\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\think\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-nxljb91b\setup.py", line 24, in run
      build_csrc()
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-nxljb91b\setup.py", line 18, in build_csrc
      subprocess.check_call(['cmake', os.path.join(base_path, 'csrc')], cwd=build_path)
    File "C:\Users\think\Anaconda3\lib\subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-build-nxljb91b\\csrc']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dirt
  Running setup.py clean for dirt
Failed to build dirt
DEPRECATION: Could not build wheels for dirt which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: dirt
    Running setup.py install for dirt ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\think\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-build-nxljb91b\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-build-nxljb91b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-m5d0covw\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\think\Anaconda3\Include\dirt'
         cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-nxljb91b\
    Complete output (31 lines):
    running install
    running build
    CMake Error: The current CMakeCache.txt directory C:/Users/Public/Documents/Wondershare/CreatorTemp/pip-req-build-nxljb91b/build/CMakeCache.txt is different than the directory g:/Hand-imitation-learning/dirt/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
    CMake Error: The source "C:/Users/Public/Documents/Wondershare/CreatorTemp/pip-req-build-nxljb91b/csrc/CMakeLists.txt" does not match the source "G:/Hand-imitation-learning/dirt/csrc/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-nxljb91b\setup.py", line 50, in <module>
        'Programming Language :: Python :: 3.7',
      File "C:\Users\think\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\think\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\think\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\think\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\think\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\think\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\think\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\think\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-nxljb91b\setup.py", line 24, in run
        build_csrc()
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-nxljb91b\setup.py", line 18, in build_csrc
        subprocess.check_call(['cmake', os.path.join(base_path, 'csrc')], cwd=build_path)
      File "C:\Users\think\Anaconda3\lib\subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-build-nxljb91b\\csrc']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\think\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-build-nxljb91b\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-build-nxljb91b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-m5d0covw\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\think\Anaconda3\Include\dirt' Check the logs for full command output.

**Comment by pmh47** [comment]
Unfortunately Windows is not supported -- only Linux -- due to lack of support for cuda/gl interop.

**Comment by huangfaan** [comment]
> due to lack of support for cuda/gl interop.

Please, when does it support on Win10 platform？or could you tell me any ways?
