### ISSUE TITLE
error of 'pip install .'

### ISSUE THREAD

**Issue by huangfaan** [pmh47/dirt#99]
ERROR: Command errored out with exit status 1:
   command: /home/nd/anaconda3/envs/ms3d-dirt/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6ksil0ko/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6ksil0ko/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-a_zejgln
       cwd: /tmp/pip-req-build-6ksil0ko/
  Complete output (49 lines):
  running bdist_wheel
  running build
  -- The CXX compiler identification is GNU 7.5.0
  -- The CUDA compiler identification is NVIDIA 9.1.85
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Detecting CUDA compiler ABI info
  -- Detecting CUDA compiler ABI info - done
  -- Check for working CUDA compiler: /usr/bin/nvcc - skipped
  -- Detecting CUDA compile features
  -- Detecting CUDA compile features - done
  CMake Error at /home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find OpenGL (missing: EGL)
  Call Stack (most recent call first):
    /home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    /home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindOpenGL.cmake:433 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    CMakeLists.txt:5 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-6ksil0ko/build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-6ksil0ko/setup.py", line 53, in <module>
      'Programming Language :: Python :: 3.7.10',
    File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-6ksil0ko/setup.py", line 26, in run
      build_csrc()
    File "/tmp/pip-req-build-6ksil0ko/setup.py", line 19, in build_csrc
      subprocess.check_call(['cmake', os.path.join(base_path, 'csrc')], cwd=build_path)
    File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-6ksil0ko/csrc']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dirt
  Running setup.py clean for dirt
Failed to build dirt
Installing collected packages: dirt
    Running setup.py install for dirt ... error
    ERROR: Command errored out with exit status 1:
     command: /home/nd/anaconda3/envs/ms3d-dirt/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6ksil0ko/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6ksil0ko/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l6tdelg7/install-record.txt --single-version-externally-managed --compile --install-headers /home/nd/anaconda3/envs/ms3d-dirt/include/python3.7m/dirt
         cwd: /tmp/pip-req-build-6ksil0ko/
    Complete output (39 lines):
    running install
    running build
    CMake Error at /home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
      Could NOT find OpenGL (missing: EGL)
    Call Stack (most recent call first):
      /home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
      /home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindOpenGL.cmake:433 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:5 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-6ksil0ko/build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-6ksil0ko/setup.py", line 53, in <module>
        'Programming Language :: Python :: 3.7.10',
      File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-6ksil0ko/setup.py", line 26, in run
        build_csrc()
      File "/tmp/pip-req-build-6ksil0ko/setup.py", line 19, in build_csrc
        subprocess.check_call(['cmake', os.path.join(base_path, 'csrc')], cwd=build_path)
      File "/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-6ksil0ko/csrc']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/nd/anaconda3/envs/ms3d-dirt/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6ksil0ko/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6ksil0ko/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l6tdelg7/install-record.txt --single-version-externally-managed --compile --install-headers /home/nd/anaconda3/envs/ms3d-dirt/include/python3.7m/dirt Check the logs for full command output.

Sorry, i am a rookie, could you help me to solve it in details, my cuda version is 10.1.243

**Comment by huangfaan** [comment]
The output of ls -l /usr/lib/*/*GL* is:
lrwxrwxrwx 1 root root      22 5月  10  2019 /usr/lib/i386-linux-gnu/libGLdispatch.so.0 -> libGLdispatch.so.0.0.0
-rw-r--r-- 1 root root  317024 5月  10  2019 /usr/lib/i386-linux-gnu/libGLdispatch.so.0.0.0
lrwxrwxrwx 1 root root      14 5月  10  2019 /usr/lib/i386-linux-gnu/libGL.so.1 -> libGL.so.1.0.0
-rw-r--r-- 1 root root  390680 5月  10  2019 /usr/lib/i386-linux-gnu/libGL.so.1.0.0
lrwxrwxrwx 1 root root      16 6月  12  2020 /usr/lib/i386-linux-gnu/libGLX_indirect.so.0 -> libGLX_mesa.so.0
lrwxrwxrwx 1 root root      20 6月  12  2020 /usr/lib/i386-linux-gnu/libGLX_mesa.so.0 -> libGLX_mesa.so.0.0.0
-rw-r--r-- 1 root root  502108 6月  12  2020 /usr/lib/i386-linux-gnu/libGLX_mesa.so.0.0.0
lrwxrwxrwx 1 root root      15 5月  10  2019 /usr/lib/i386-linux-gnu/libGLX.so.0 -> libGLX.so.0.0.0
-rw-r--r-- 1 root root   71304 5月  10  2019 /usr/lib/i386-linux-gnu/libGLX.so.0.0.0
lrwxrwxrwx 1 root root      20 3月  11 21:56 /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0 -> libEGL_mesa.so.0.0.0
-rw-r--r-- 1 root root  259448 6月  12  2020 /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0.0.0
lrwxrwxrwx 1 root root      26 12月 30 06:22 /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.0 -> libEGL_nvidia.so.460.32.03
-rw-r--r-- 1 root root 1312784 12月 28 02:52 /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.460.32.03
lrwxrwxrwx 1 root root      15 5月  10  2019 /usr/lib/x86_64-linux-gnu/libEGL.so -> libEGL.so.1.0.0
lrwxrwxrwx 1 root root      15 3月  11 21:56 /usr/lib/x86_64-linux-gnu/libEGL.so.1 -> libEGL.so.1.0.0
-rw-r--r-- 1 root root   80448 5月  10  2019 /usr/lib/x86_64-linux-gnu/libEGL.so.1.0.0
lrwxrwxrwx 1 root root      22 5月  10  2019 /usr/lib/x86_64-linux-gnu/libGLdispatch.so -> libGLdispatch.so.0.0.0
lrwxrwxrwx 1 root root      22 3月  11 21:56 /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 -> libGLdispatch.so.0.0.0
-rw-r--r-- 1 root root  612792 5月  10  2019 /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0
lrwxrwxrwx 1 root root      32 12月 30 06:22 /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.1 -> libGLESv1_CM_nvidia.so.460.32.03
-rw-r--r-- 1 root root   67880 12月 28 02:51 /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.460.32.03
lrwxrwxrwx 1 root root      21 5月  10  2019 /usr/lib/x86_64-linux-gnu/libGLESv1_CM.so -> libGLESv1_CM.so.1.0.0
lrwxrwxrwx 1 root root      21 5月  10  2019 /usr/lib/x86_64-linux-gnu/libGLESv1_CM.so.1 -> libGLESv1_CM.so.1.0.0
-rw-r--r-- 1 root root   43328 5月  10  2019 /usr/lib/x86_64-linux-gnu/libGLESv1_CM.so.1.0.0
lrwxrwxrwx 1 root root      29 12月 30 06:22 /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.2 -> libGLESv2_nvidia.so.460.32.03
-rw-r--r-- 1 root root  117032 12月 28 02:51 /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.460.32.03
lrwxrwxrwx 1 root root      18 5月  10  2019 /usr/lib/x86_64-linux-gnu/libGLESv2.so -> libGLESv2.so.2.0.0
lrwxrwxrwx 1 root root      18 3月  11 21:56 /usr/lib/x86_64-linux-gnu/libGLESv2.so.2 -> libGLESv2.so.2.0.0
-rw-r--r-- 1 root root   72000 5月  10  2019 /usr/lib/x86_64-linux-gnu/libGLESv2.so.2.0.0
lrwxrwxrwx 1 root root      14 5月  10  2019 /usr/lib/x86_64-linux-gnu/libGL.so -> libGL.so.1.0.0
lrwxrwxrwx 1 root root      14 3月  11 21:56 /usr/lib/x86_64-linux-gnu/libGL.so.1 -> libGL.so.1.0.0
-rw-r--r-- 1 root root  567624 5月  10  2019 /usr/lib/x86_64-linux-gnu/libGL.so.1.0.0
lrwxrwxrwx 1 root root      15 3月  11 21:56 /usr/lib/x86_64-linux-gnu/libGLU.so.1 -> libGLU.so.1.3.1
-rw-r--r-- 1 root root  453352 5月  22  2016 /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
lrwxrwxrwx 1 root root      16 3月  11 21:56 /usr/lib/x86_64-linux-gnu/libGLX_indirect.so.0 -> libGLX_mesa.so.0
lrwxrwxrwx 1 root root      20 3月  11 21:56 /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0 -> libGLX_mesa.so.0.0.0
-rw-r--r-- 1 root root  488312 6月  12  2020 /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0
lrwxrwxrwx 1 root root      26 12月 30 06:22 /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0 -> libGLX_nvidia.so.460.32.03
-rw-r--r-- 1 root root 1211504 12月 28 02:50 /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.460.32.03
lrwxrwxrwx 1 root root      15 5月  10  2019 /usr/lib/x86_64-linux-gnu/libGLX.so -> libGLX.so.0.0.0
lrwxrwxrwx 1 root root      15 3月  11 21:56 /usr/lib/x86_64-linux-gnu/libGLX.so.0 -> libGLX.so.0.0.0
-rw-r--r-- 1 root root   68144 5月  10  2019 /usr/lib/x86_64-linux-gnu/libGLX.so.0.0.0
lrwxrwxrwx 1 root root      18 5月  10  2019 /usr/lib/x86_64-linux-gnu/libOpenGL.so -> libOpenGL.so.0.0.0
lrwxrwxrwx 1 root root      18 5月  10  2019 /usr/lib/x86_64-linux-gnu/libOpenGL.so.0 -> libOpenGL.so.0.0.0
-rw-r--r-- 1 root root  186688 5月  10  2019 /usr/lib/x86_64-linux-gnu/libOpenGL.so.0.0.0

**Comment by huangfaan** [comment]
my tensorflow-gpu version 1.13.1, my cuda version is cuda_10.1.243_418.87.00_linux

**Comment by huangfaan** [comment]
It seems that the reson is here:

cwd: /tmp/pip-req-build-6ksil0ko/
Complete output (39 lines):
running install
running build
CMake Error at /home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
Could NOT find OpenGL (missing: EGL)
Call Stack (most recent call first):
/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
/home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindOpenGL.cmake:433 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
CMakeLists.txt:5 (find_package)

Could NOT find OpenGL，Missing EGL？

**Comment by aapatre** [comment]
Try running these in your terminal first:

`sudo apt-get update`
'sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev'

**Comment by aapatre** [comment]
Seems that OpenGL an it's dependencies were missing in your case
Also, try installing PyOpenGL:
`pip install PyOpenGL PyOpenGL_accelerate`

**Comment by huangfaan** [comment]
> pip install PyOpenGL PyOpenGL_accelerate
PyOpenGL PyOpenGL_accelerate were installed before!

Requirement already satisfied: PyOpenGL in /home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages (3.1.5)
Requirement already satisfied: PyOpenGL_accelerate in /home/nd/anaconda3/envs/ms3d-dirt/lib/python3.7/site-packages (3.1.5)

but 'sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev' failed:

正在设置 cuda-toolkit-11-2 (11.2.1-1) ...
Setting alternatives
update-alternatives: 错误: 候选项路径 /usr/local/cuda-11.2 不存在
dpkg: 处理软件包 cuda-toolkit-11-2 (--configure)时出错：
 installed cuda-toolkit-11-2 package post-installation script subprocess returned error exit status 2
dpkg: 依赖关系问题使得 cuda-11-2 的配置工作不能继续：
 cuda-11-2 依赖于 cuda-toolkit-11-2 (>= 11.2.1)；然而：
  软件包 cuda-toolkit-11-2 尚未配置。

dpkg: 处理软件包 cuda-11-2 (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 cuda 的配置工作不能继续：
 cuda 依赖于 cuda-11-2 (>= 11.2.1)；然而：
  软件包 cuda-11-2 尚未配置。

dpkg: 处理软件包 cuda (--configure)时出错：
 依赖关系问题 - 仍未被配置
因为错误消息指示这是由于上一个问题导致的错误，没有写入 apport 报告。
                                                                    因为错误消息指示这是由于上一个问题导致的错误，没有写入 apport 报告。
                                                        在处理时有错误发生：
 cuda-toolkit-11-2
 cuda-11-2
 cuda
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by huangfaan** [comment]
my main problem is 'Could NOT find OpenGL (missing: EGL)', I don't know where to set 'EGL_LIBRARIES'? Who can help me?

**Comment by sugarbeet34** [comment]
Hi, did you solve it?
